### ISSUE TITLE
Add deepEquals

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/seamless-immutable#1]
Add a `deepEquals` to both `ImmutableArray` and `ImmutableObject` which skips checking any branches where the children are `===` and immutable.

**Comment by narqo** [comment]
Maybe there should be `Immutable.is()` static method, which would have the same semantic [ES6's `Object.is()` has][1]?

The API may look like this: `Immutable.is(obj1, obj2)` to check whether objects are equal by value. 

[1]: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is

**Comment by rtfeldman** [comment]
I wouldn't want to confuse people; `Object.is` only differs from `===` in the specific cases of `NaN`, `0`, and `-0` (and [handles object comparisons in the same way as ===](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Sameness])), whereas the `deepEquals` I'm referring to would compare the contents of objects, like what [Underscore's _.isEqual](http://underscorejs.org/#isEqual) does.

**Comment by narqo** [comment]
You're absolutely right. Somehow I decided that `Object.is()` compares objects by there values, not by "identity". My bad, sorry.

**Comment by n1k0** [comment]
+1, that would greatly help checking if an immutable structure has actually changed. 

Nit: How about a shorter name, eg. `equals`, or `eq`?

**Comment by abritinthebay** [comment]
semantically `equals` is nicer - easy to discover on an object too ("What's this do? Oh.. it's an equals function").

**Comment by Aetet** [comment]
Hello. What is status for deep equality between objects? What is api for that right now? @rtfeldman

**Comment by rtfeldman** [comment]
@Aetet I have [a WIP branch](https://github.com/rtfeldman/seamless-immutable/tree/deep-equals) that implements it, but needs a bunch of tests before it can go on `master`. I haven't had time to work on it, and realistically won't in the near future.

**Comment by rtfeldman** [comment]
There doesn't seem to be much demand for this, so I'm going to close this for now.

**Comment by juanger** [comment]
@rtfeldman Hi, are you still interested in this? If so, I'd like to give it a try, rebase your branch and write tests

**Comment by theogravity** [comment]
i'm also interested in this feature as well, have some deeply nested objects and doing something like this in react:

```
shouldComponentUpdate(nextProps) {
    // this.props.obj is immutable

   return this.props.obj.equals(nextProps.obj)
}
```
