### ISSUE TITLE
Suggestion: merge method for array implementation

### ISSUE THREAD

**Issue by OEvgeny** [rtfeldman/seamless-immutable#106]
I'm looking for a good way to merge immutable array with a new one I think it will be really cool to do things like so:
```js
/*
storeUsers = [{id:0, name: 'James'}, undefined, {id:2, name:'Jane'}]
*/
let users = Immutable(storeUsers);
let newUsers = [null, {id:1, name: 'Jack'}];
users = users.merge(newUsers);
```

I think it will be easy to implement, and I can try with pull-request. What are you thought on this?

**Comment by rtfeldman** [comment]
Thanks for taking the time to write this up, but I prefer to keep the API small and compact, so I'd rather not add this. :smiley:

**Comment by OEvgeny** [comment]
@rtfeldman good point :smile:
