### ISSUE TITLE
a.without(1) vs a.without('1')

### ISSUE THREAD

**Issue by Poordeveloper** [rtfeldman/seamless-immutable#112]
a.set(1, 2)
a.without(1) does not work, but '1' works.

**Comment by rtfeldman** [comment]
This is because JavaScript objects only use strings for keys, not numbers.

**Comment by Poordeveloper** [comment]
But a[1] and a['1'] both work, how do you explain?

**Comment by rtfeldman** [comment]
JavaScript treats `a[1]` as the same as `a["1"]` when `a` is an object.
