### ISSUE TITLE
Seamless-immutable should support AMD modules

### ISSUE THREAD

**Issue by max-winderbaum** [rtfeldman/seamless-immutable#117]
I'm happy to make a PR expanding the UMD to accept an AMD request, but it's a hassle to shim seamless-immutable in my RequireJS project. Please let me know if there's a reason this hasn't been implemented, and if you'd like me to add it in :)

**Comment by rtfeldman** [comment]
No reason except that I don't use AMD. Happy to accept a PR! :smile:
