### ISSUE TITLE
Immutable.from

### ISSUE THREAD

**Issue by ericclemmons** [rtfeldman/seamless-immutable#123]
It's common convention (especially to thousands using ESLint presets) to require `new` before capitalized functions (`Immutable)`, as those are typically constructors:
> http://eslint.org/docs/rules/new-cap

Would you accept a PR for `Immutable.from(...)`, which is simply an alias to `Immutable`?

This would allow users to maintain convention and avoid littering their code with `// eslint-disable-line` everywhere they use this project.

👍 on this project BTW!

**Comment by rtfeldman** [comment]
Sure, makes sense to me! 😃

**Comment by ericclemmons** [comment]
Work is being done in #126...

**Comment by rtfeldman** [comment]
Released in 6.1.0. Thanks again @ericclemmons!
