### ISSUE TITLE
Using 'without' method to prevent circular references

### ISSUE THREAD

**Issue by Snowshield** [rtfeldman/seamless-immutable#125]
`Without `can be very usefull to prevent circular references in situations like that.
```
let objA = {a : 1},
    objB = {objA, b : 2};
objA.objB = objB;
let ImmutableA = Immutable(objA).without("objB");
// ImmutableError: Attempt to construct Immutable from a deeply nested ...
```
Can you make option or function `without`?
```
let ImmutableA = Immutable(objA, {without : ["objB"]});
// no error
```

**Comment by rtfeldman** [comment]
Why not just transform the argument before calling `Immutable` on it?

**Comment by Snowshield** [comment]
Argument object may all propetiies to work properly.
Second way is to clone it for N depth, delete props and send cloned to `Immutable`.
But its not equal if object has depth L>N.

**Comment by rtfeldman** [comment]
This use case seems too narrow to justify the added complexity, sorry!
