### ISSUE TITLE
Deep Merge With Nested Identical Array Returns False

### ISSUE THREAD

**Issue by alexcurtis** [rtfeldman/seamless-immutable#154]
Please see: https://github.com/rtfeldman/seamless-immutable/issues/94.
I still think this is a valid issue -- I am came across it myself. Could we please look into it?

**Comment by rtfeldman** [comment]
> I still think this is a valid issue

I respectfully disagree. 🙂

From the original:

> A `.merge` with `{deep: true}` of two identical objects that contain an array is returning a new object.

I expect that changing this behavior would be a serious performance regression. You would have to do comparisons at every single step of the merge, to check whether anything had changed. That is not free, and we should not act as though it were!
