### ISSUE TITLE
Structural sharing vs shallow copy

### ISSUE THREAD

**Issue by alisman** [rtfeldman/seamless-immutable#163]
I'm having trouble understanding the difference and the performance implications (especially in an app with a large amount of data in the frontend).  Can anyone advise?  Sorry if this isn't the right forum.  Not sure where else to ask as this is an esoteric issue.

**Comment by rtfeldman** [comment]
> Sorry if this isn't the right forum. Not sure where else to ask as this is an esoteric issue.

Sorry, but it's not the right forum. 🙂

I'd try StackOverflow!
