### ISSUE TITLE
How do we measure the size of an Immutable data structure?

### ISSUE THREAD

**Issue by slashwhatever** [rtfeldman/seamless-immutable#168]
Immutable.js has a simple size member that allows you to check the existence of data in a collection (Map or List)

How do we do the same in seamless-immutable?

So we should be able to do something similar to this;

```
const myImmutable = Immutable({the: "forests", will: "echo", with: "laughter"})
return myImmutable.size > 0 ? 'Collection populated :)' : 'Collection empty :('
```

**Comment by crudh** [comment]
@slashwhatever the result in your example is a javascript object, not a collection of any type. So you have to check the number of keys in the object with `Object.keys(myImmutable).length` or use something like `_.size` from lodash.

If you make an array immutable you can just use `.length` on it or again `_.size` from lodash.

**Comment by slashwhatever** [comment]
Thanks for the input @crudh. The fact we have to do something different for objects vs arrays is kinda my point. ImmutableJS allows you to use the same method name regardless of the type you're working with.

**Comment by crudh** [comment]
@slashwhatever yes, but the reasoning of seamless is that the types should be plain javascript types, with as few modifications as possible. So `_.size` is probably the best suggestion for this use case.

**Comment by slashwhatever** [comment]
@crudh understood :)
