### ISSUE TITLE
Merge ought error out when passed a string. 

### ISSUE THREAD

**Issue by raorao** [rtfeldman/seamless-immutable#17]
current behavior:

```javascript
  foo = Immutable({key: 'value'})
  // Object {key: 'value'}
  foo.merge('whoops')
  // Object {0: "w", 1: "h", 2: "o", 3: "o", 4: "p", 5: "s", key: 'value'}
```
While this conforms with JavaScript strategy of coercing strings into objects, it leads to crazy errors. FWIW, lodash simply ignores strings that are passed to merge.

**Comment by n1k0** [comment]
+1
