### ISSUE TITLE
Cursors

### ISSUE THREAD

**Issue by natew** [rtfeldman/seamless-immutable#18]
Just wondering before I test this out, I use cursors to great effect alongside the fynx immutable-flux library. I'd definitely want to test this library out as I am only targeting mobile platforms so I don't need old IE support.

Plans for cursors, compat with other cursor impls?

**Comment by rtfeldman** [comment]
Currently no plans for cursors, sorry!

**Comment by seanhess** [comment]
@natew I think cursors can be implemented separately from the data structure. See here: https://github.com/kualico/easy-cursors

**Comment by rtfeldman** [comment]
Indeed!
