### ISSUE TITLE
v7.0.0 seems broken in React Native environment

### ISSUE THREAD

**Issue by messense** [rtfeldman/seamless-immutable#180]
Just upgraded from 6.1.1, causing import error.

**Comment by rtfeldman** [comment]
I need a lot more information than this.

Please feel to reopen with a description that someone can act on. 🙂

**Comment by messense** [comment]
![image](https://cloud.githubusercontent.com/assets/1556054/21087829/58c3310a-c064-11e6-9fdc-2b4c58764b0c.png)

Downgraded to v6.1.1 works fine.

**Comment by messense** [comment]
And the React Native packager hangs on transforming when this error occurred.

**Comment by rtfeldman** [comment]
What happens if you go into `node_modules/seamless-immutable/package.json` and delete the `"browser":` entry?

**Comment by messense** [comment]
@rtfeldman Works fine after deleting `browser` entry!

**Comment by rtfeldman** [comment]
Hm, ok - what if you leave the `browser` entry there, but add another entry that's exactly the same as the `browser` one except it says `"react-native"` instead of `"browser"`?

**Comment by messense** [comment]
@rtfeldman Still get the error.

**Comment by messense** [comment]
It works when I leave the `browser` entry there, but add another entry that's exactly the same as the `main` one except it says `"react-native"` instead of `"main"`

**Comment by rtfeldman** [comment]
@messense please reopen if `7.0.1` doesn't fix this!
