### ISSUE TITLE
How do I get rid of the immutable methods on an array?

### ISSUE THREAD

**Issue by peterpme** [rtfeldman/seamless-immutable#185]
Hello @rtfeldman, your library is awesome! Thanks for making my life easier!

I have one issue I can't seem to figure out, (maybe it's late) but how do I get rid of the immutable properties from an array?

I'd like to make an HTTP request but the rest of the information is being sent down as well!

Thank you :)

**Comment by theogravity** [comment]
Have you tried using the static version of the library?

Eg

```
const Immutable = require('seamless-immutable').static

const data = Immutable.from({ data: []})
```

The static version of the API should not have methods attached AFAIK

**Comment by peterpme** [comment]
Hey @theogravity thanks for getting back to me! This is great!
