### ISSUE TITLE
.npmignore contents is different in NPM package

### ISSUE THREAD

**Issue by nazar-pc** [rtfeldman/seamless-immutable#187]
Contents of `.npmignore` in master branch contains few extra files:
```
seamless-immutable.development.min.js
seamless-immutable.development.js
seamless-immutable.production.min.js
```

However, these files (thankfully) are not listed in 7.0.1 version of the NPM package's file.
Looks like you have some llocal changes not committed to repository, maybe remove these files from `.npmignore` in repository as well?

**Comment by crudh** [comment]
This was fixed in #205, closing.
