### ISSUE TITLE
Add function for deep merge?

### ISSUE THREAD

**Issue by crudh** [rtfeldman/seamless-immutable#19]
I did this a few days ago in a fork:
https://github.com/crudh/seamless-immutable/commit/8552c98fd177cdf48d560758caa1ab8bee7df92f

mergeDeep is like the normal merge function but it merges all children objects too. Right now there is no code reuse from the normal merge (except for 2 lines it is a copy and paste of merge) and the tests are simple copies from the normal merge.

Before cleaning it up for my fork I just wanted to know if there is any interest to pull it back into master? If so, are there any preferences for naming, code reuse and so on?

**Comment by rtfeldman** [comment]
I dig it! Test duplication is no problem, but from an API perspective I'd prefer if this were an optional boolean passed to `merge` to enable deep merging.

Would love to see a Pull Request for this. :+1:

**Comment by crudh** [comment]
Ok! Instead of a boolean, what to you think about a `mergeWith` function or similar that takes a config object first (which the normal merge can use under the covers) so more config can be added later if needed?

`obj1.mergeWith({deep: true}, obj2);`

I have a use case where I would like to supply a custom merger sometimes, that could fit into this strategy.

But if you don't like it I will do a PR with the boolean.

**Comment by RangerMauve** [comment]
IMO it's usually nicer to have configs or optional flags as the last argument in a function and not the first.

**Comment by crudh** [comment]
@RangerMauve I agree in general, but if the `With` in the function name is for merging _with_ the config I think it is natural if the mandatory config is first. Especially if it is a merge with multiple objects like:

`obj1.mergeWith({deep: true}, obj2, obj3, obj4, obj5);`

But it doesn't matter much either way. Any thoughts @rtfeldman?

**Comment by RangerMauve** [comment]
@crudh That's a good point, actually. And it'd work well once [rest paramters](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters) become mainstream.

**Comment by rtfeldman** [comment]
Good points all around. My preference is to change the existing `merge` as follows:

1. It now always takes exactly one or exactly two arguments.
2. The first argument works the same as always: you can pass it one object to merge, or an array of them.
3. The second argument is optional, and is a configuration object that currently supports only `{deep: true}`

Sound good?

**Comment by crudh** [comment]
Sounds good to me!
