### ISSUE TITLE
Immutable.isImmutable is not documented in README

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/seamless-immutable#192]
It's exposed, so it seems reasonable to document it.

https://github.com/rtfeldman/seamless-immutable/blob/master/src/seamless-immutable.js#L696

Happy to accept a PR for this if anyone is interested in contributing one!

**Comment by arthur31416** [comment]
Hi. I just opened a PR to document it. I'd be glad to tweak if necessary.
