### ISSUE TITLE
Getting "Error: Cannot find module 'seamless-immutable'" in version 7.1.0 but not 7.0.1

### ISSUE THREAD

**Issue by LukeusMaximus** [rtfeldman/seamless-immutable#206]
My package that depends on this one suffers the following error when browserifying this module:
`Error: Cannot find module 'seamless-immutable'`
This occurs in the version 7.1.0 but not 7.0.1.
Shrinkwrapping solves this problem for now.
Is this caused by the changes to the package.json "browser" or "main" fields?

**Comment by dentrado** [comment]
I've made a PR that should fix the problem: https://github.com/rtfeldman/seamless-immutable/pull/205

**Comment by rtfeldman** [comment]
@LukeusMaximus should be fixed in 7.1.1

**Comment by LukeusMaximus** [comment]
Yup, all fixed.
