### ISSUE TITLE
update mutable objects in a callback?

### ISSUE THREAD

**Issue by seanhess** [rtfeldman/seamless-immutable#21]
Like how immutable-js does it, but maybe it passes a mutable copy into the function? 

Like this?

```
var item = Immutable({name: "bob"})

// new Item is immutable, obj is mutable
var newItem = item.mutate(function(obj) {
   obj.name = "henry"
})
```

The rationale is that it's really handy to be able to make multiple changes to an object in one go, and get an immutable object back. I'd prefer to have that callback be an immutable function itself, but I can't think of a good way to set properties without breaking type safety (imagine trying to use your `.merge` with flow).

**Comment by rtfeldman** [comment]
I haven't come across this use case yet, but it turns out you can already do this pretty cleanly with [`asMutable`](https://github.com/rtfeldman/seamless-immutable#asmutable):

```javascript
var item = Immutable({name: "bob"});

// new Item is immutable, obj is mutable
var newItem = (function(obj) {
   obj.name = "henry";
   return obj;
})(item.asMutable());
```

**Comment by rtfeldman** [comment]
@seanhess Seems like this would address your use case, yeah? :smiley:

**Comment by seanhess** [comment]
Cool! But wouldn't newItem be mutable afterward?

**Comment by rtfeldman** [comment]
True! Fixed:

```javascript
var item = Immutable({name: "bob"});

// new Item is immutable, obj is mutable
var newItem = (function(obj) {
   obj.name = "henry";
   return Immutable(obj);
})(item.asMutable());
```

**Comment by seanhess** [comment]
I still think something more terse might be a good addition to the library, but nothing I can't fix with my own function. Thanks for being awesome!

**Comment by rtfeldman** [comment]
Glad it was helpful! :smile_cat:
