### ISSUE TITLE
How to update react state correctly?

### ISSUE THREAD

**Issue by SergeyAlexeev** [rtfeldman/seamless-immutable#227]
I'm using seamlees-immutable to make the state of my component immutable.

My code looks like below:

    export class MyComponent extends React.PureComponent {
      constructor(props) {
        //...
        this.state = Immutable({
          selectedItems: []
        });
      }

      this.updateSelectedItems = (selectedItems) => {
        this.setState({ selectedItems  });
      };
    }

In the `updateSelectedItems ` function I'd like to update the state. So, I use the `setState` function.  It works, but I'm worried if this a correct way? In this case, I update immutable structure directly. In ImmutableJS I use its API to update the state, it looks like this:

     this.updateSelectedItems = (selectedItems) => {
      this.setState(({data}) => ({
        data: data.update('selectedItems', selectedItems => selectedItems)
      }));
    };

Should I use something like this here?

**Comment by chj-damon** [comment]
@SergeyAlexeev hi there. I'm wondering the same thing as you were. Is it the right way to do so with seamless-immutable? I see there's no difference as what I usually did without it.
