### ISSUE TITLE
.without() for nested data structure

### ISSUE THREAD

**Issue by yirichie** [rtfeldman/seamless-immutable#236]
```
newState = {
  OFFER_CAMPAIGNS: {
    data: {
      offers: {
         100: {},
         200: {}
      }
    }
  }
}
```

I'm trying to remove the property '100', but the ".without()" method doesn't show how to access a prop inside a nested data structure. Is this possible?

**Comment by Dictory** [comment]
`newState.updateIn(['OFFER_CAMPAING', 'data', offers], offers => offers.without('100'));`
