### ISSUE TITLE
Update documentation to included undocumented array methods

### ISSUE THREAD

**Issue by beausmith** [rtfeldman/seamless-immutable#238]
The docs for [Immutable Array](https://github.com/rtfeldman/seamless-immutable/blob/master/README.md#immutable-array) do not contain documentation for the following [array methods](https://github.com/rtfeldman/seamless-immutable/blob/ea3676d4e3b857e1608e4698f75590714796b888/src/seamless-immutable.js#L199-L206): 
- `set`
- `setIn`
- `update`
- `updateIn`
- `getIn`

**Comment by crudh** [comment]
That would be really nice, a PR would be great!
