### ISSUE TITLE
Internet Explorer tests are failing

### ISSUE THREAD

**Issue by modulitos** [rtfeldman/seamless-immutable#243]
I see that this library claims support for IE9+, but I see that the tests are failing for all IE browsers. 

I tried looking into the test logs for IE11 tests here: https://saucelabs.com/beta/tests/6893bc7e1ee04ca08a59a45a07e698c3/commands#4 but I couldn't find any clues about what is causing the tests to fail.

Why are these tests failing? Does this mean that seamless-immutable is not compatible with IE?

**Comment by winstonwolff** [comment]
Does the failure look like this?  I see this on MacOS / node.v8.9.1

```
>> ReferenceError: File is not defined
>>     at module.exports (/Users/winstonw/clients/nitidbit/git/seamless-immutable/test/TestUtils.js:145:30)
>>     at /Users/winstonw/clients/nitidbit/git/seamless-immutable/test/Immutable.isImmutable.spec.js:13:19
>>     at Array.forEach (<anonymous>)
>>     at Object.<anonymous> (/Users/winstonw/clients/nitidbit/git/seamless-immutable/test/Immutable.isImmutable.spec.js:11:3)
>>     at Module._compile (module.js:635:30)
>>     at Object.Module._extensions..js (module.js:646:10)
>>     at Module.load (module.js:554:32)
>>     at tryModuleLoad (module.js:497:12)
>>     at Function.Module._load (module.js:489:3)
>>     at Module.require (module.js:579:17)
```

**Comment by crudh** [comment]
PR #247 should fix the File/Blob problems (since they aren't available in Node). But it doesn't fix the zuul/Saucelabs tests regarding IE and other things. Some more info here: #246

**Comment by crudh** [comment]
The tests for IE might be failing since the tests uses `Promise` which isn't available in IE. But the actual runtime code has no dependencies on `Promise`, so it should work in IE.

**Comment by crudh** [comment]
The tests have been fixed but we had to drop the browser tests because of changes at saucelabs. I hope they (or similar) can be brought back soon. But as far as I know the latest ones did show that everything was working in IE9+ as the README states.
