### ISSUE TITLE
Custom merger function

### ISSUE THREAD

**Issue by crudh** [rtfeldman/seamless-immutable#26]
I have a use case where I would like to override the normal merge behaviour for specific types or conditions. 

I was thinking that you could send a custom merger function as a parameter with the config to `merge`. If that function returns `undefined` the merge would proceed as normal. If it returns something else then that value will be used instead of the normal rules.

A simple example that combines arrays instead of replacing them:
```
var one = {
  id: 3,
  list: [1, 3, 5]
};

var two = {
  id: 3,
  list: [2, 4, 6]
};

var arrayConcatMerger = function(current, other) {
  if (current instanceof Array && other instanceof Array) {
    return current.concat(other);
  }

  return;
}

var result = one.merge(two, {merger: arrayConcatMerger});
```

And the result would be:
```
 {
  id: 3,
  list: [1, 3, 5, 2, 4, 6]
};
```

This would allow you to do more complex stuff like merging objects in an array if there exists an object with the same id in both arrays and so on.

**Comment by rtfeldman** [comment]
:+1:  Makes sense...giving it another optional parameter is no big deal since it no longer accepts varargs, and the performance impact should be trivial (one extra conditional per iteration) in the normal case.

**Comment by tusharmath** [comment]
What should the custom merger return if I want to delete a particular key?

**Comment by FriOne** [comment]
@rtfeldman could you move it to README?
