### ISSUE TITLE
Any difference with deepCopy?

### ISSUE THREAD

**Issue by SnowFlowers** [rtfeldman/seamless-immutable#260]
function asMutableObject(opts) {
    var result = instantiateEmptyObject(this), key;

    if(opts && opts.deep) {
      for (key in this) {
        if (this.hasOwnProperty(key)) {
          result[key] = asDeepMutable(this[key]);
        }
      }
    } else {
      for (key in this) {
        if (this.hasOwnProperty(key)) {
          result[key] = this[key];
        }
      }
    }

    return result;
  }

why dont use lodash.deepCopy? lazy computed more?

**Comment by crudh** [comment]
seamless-immutable has 0 dependencies and we want to keep it that way so we don't force lodash on anyone.
