### ISSUE TITLE
Question about `.push`

### ISSUE THREAD

**Issue by ivan-kleshnin** [rtfeldman/seamless-immutable#35]
What do you think about making `push` immutable operation (returning new extended array) instead of blocking it? The drawback is that you change conventional (but broken) API, but the benefit is that people could stop to use `concat` where `push` will satisfy. My arguments:

1) Barely noone is rely on native `push` return value (updated array length :disappointed:) right now so this API "change" shouldn't surprise or hurt. 
2) You don't modify `Array.prototype` so this is safe.
3) You already added some unexisting but crucial methods like `flatMap` –
API is already changed why not fix `push` then.

**Comment by crudh** [comment]
I think the biggest drawback is that you have to do `push` differently for normal and immutable arrays, and there isn't anything telling you that you are doing it wrong if you `push` on an immutable array and don't take care of the result.

It can be especially confusing if you have a code base where you use both regular arrays and immutable arrays.

**Comment by ivan-kleshnin** [comment]
I think that's pretty easy to differ visually:

```js
x.push(y); // mutable push
...
let count = x.push(y) // mutable push
...
robots = robots.push(); // immutable push
...
let robots2 = robots.push(); // immutable push 
```

**Comment by crudh** [comment]
Yeah, it is easy to differ visually. But if you are working with code that uses both mutable and immutable arrays and you do a `push` on an immutable array now you get an error and you are made aware of it during development.

With this change you might by mistake do a `push` on an immutable array and forget to handle the result and get no warning about it. It might then lead to bugs that can be tricky to locate the source of.

So you have a valid point, but I'm not personally convinced that the benefits are greater than the drawbacks. And if `push` should be changed in this way then maybe all other banned mutating methods should be changed in the same way too?

**Comment by ivan-kleshnin** [comment]
> And if push should be changed in this way then maybe all other banned mutating methods should be changed in the same way too?

Maybe. I can recall only `push` being needed all the time but, yeah, banned. What else?
Maybe a bigger picture will guide the best decision here.

**Comment by rtfeldman** [comment]
Yep, @crudh's explanation is exactly the reason behind banning the mutable methods. If there were a desire to add an alternative to `concat` for single elements, I'd call it something else, like `append`.

A separate question is whether a method like that is worth adding to the API. Is there a common use case where this would be a significant upgrade over `concat`? I have not encountered any yet, and I'm hesitant to expand the API without strong motivating use cases because that's how libraries get bloated. :smile:

**Comment by ivan-kleshnin** [comment]
Well, I was pretty sure about this proposal being rejected so no disappointment here :smile: 
Thank you guys for discussion :thumbsup: hope to give this lib a better try soon.
