### ISSUE TITLE
using seamless-immutable in a jsbin

### ISSUE THREAD

**Issue by dagda1** [rtfeldman/seamless-immutable#39]
I'm trying to use seamless-immutable in [this jsbin](http://jsbin.com/nesomi/10/edit) but whenever this line is ran:
```
var array = Immutable(["foo", "foo2", "bar", "bar2", "baz", "baz2"]);
```
I get this error:

> Uncaught TypeError: Cannot redefine property: [object Object]

And this stack trace:
```
addPropertyTo	@	seamless-immutable.js:5
makeMethodReturnImmutable	@	seamless-immutable.js:84
makeImmutableArray	@	seamless-immutable.js:94
Immutable	@	seamless-immutable.js:328
(anonymous function)	@	nesomi.js:36
applyStr	@	ember.debug.js:18054
sendEvent	@	ember.debug.js:12373
exports.default.mixin.Mixin.create.trigger	@	ember.debug.js:29705
superFunction	@	ember.debug.js:13704
EmberObject.default.extend.trigger	@	ember.debug.js:40271
superWrapper	@	ember.debug.js:17586
Renderer.default.didInsertElement	@	ember.debug.js:38923
Renderer_renderTree	@	ember.debug.js:8480
scheduledRenderTree	@	ember.debug.js:8506
Queue.invoke	@	ember.debug.js:871
Queue.flush	@	ember.debug.js:936
DeferredActionQueues.flush	@	ember.debug.js:741
Backburner.end	@	ember.debug.js:166
Backburner.run	@	ember.debug.js:221
executeTimers	@	ember.debug.js:603
(anonymous function)	@	ember.debug.js:592
```

**Comment by rtfeldman** [comment]
Hm...seems to work fine in a Node REPL:

```javascript
> var Immutable = require("seamless-immutable")
undefined
> var array = Immutable(["foo", "foo2", "bar", "bar2", "baz", "baz2"]);
undefined
> array
[ 'foo', 'foo2', 'bar', 'bar2', 'baz', 'baz2' ]
```

My first guess would be that Ember modifies `Array.prototype` in some way that is incompatible with `seamless-immutable`...do you know if that's something Ember does?

**Comment by dagda1** [comment]
Yes, you are right, ember does modify the prototype.  You can turn that off though.

Thanks

**Comment by dagda1** [comment]
I've stopped ember extending the prototypes and I get a new error:

>Uncaught ReferenceError: process is not defined

Which references this code:
```
    if (process.env.NODE_ENV === "development") {
      // Make all mutating methods throw exceptions.
      for (var index in bannedMethods) {
        banProperty(obj, bannedMethods[index]);
      }
```

Is this library node only?

Here is the updated [jsbin](http://jsbin.com/nesomi/14/edit)

**Comment by rtfeldman** [comment]
@dagda1 This is happening because you're importing the seamless-immutable source, not the compiled version (which has `process` stripped out). Try importing one of these instead:

[`seamless-immutable development mode`](https://raw.githubusercontent.com/rtfeldman/seamless-immutable/master/seamless-immutable.development.js) (with freezing and helpful exception messages)
[`seamless-immutable production mode`](https://raw.githubusercontent.com/rtfeldman/seamless-immutable/master/seamless-immutable.production.min.js) (minified, and runs faster, but doesn't freeze objects or offer helpful exception messages)

**Comment by rtfeldman** [comment]
@dagda1 Did this fix the issue you were having?

**Comment by dagda1** [comment]
Sorry, yes, thanks
