### ISSUE TITLE
Immutable doesn't freeze Date objects.

### ISSUE THREAD

**Issue by jjulicher** [rtfeldman/seamless-immutable#46]
console test: 

var mydate = Immutable(new Date());
undefined
mydate
Fri Jun 12 2015 15:24:24 GMT+1000 (AEST)
mydate.setYear(2020)
1591939464409
mydate
Fri Jun 12 2020 15:24:24 GMT+1000 (AEST)

Last entry shows Date object hasn't been made immutable.

**Comment by rtfeldman** [comment]
Sure enough! Good catch.

The solution that comes immediately to mind is to change development mode as follows:

1. Freeze Dates
2. Add a list of banned mutating methods for Dates similar to what currently exists for Arrays and Objects, and just do the same banning procedure for Dates.

Thoughts?

**Comment by jjulicher** [comment]
I can't think of any issues that come to mind. sounds good.

**Comment by rtfeldman** [comment]
Fixed by #78
