### ISSUE TITLE
document technique for updating an individual key

### ISSUE THREAD

**Issue by gregwebs** [rtfeldman/seamless-immutable#54]
with Immutable.js I can do

```
Immutable.List.of(1,2,3).update(0, x => x + 1)
```

This is useful if I have view state that is a list of 10 elements and I want to update just one of them that the user acts on.

What is the best practice for accomplishing this with seamless-immutable?

**Comment by crudh** [comment]
`Immutable([1,2,3]).map(function(x) { return x + 1 })`
or in ES6:
`Immutable([1,2,3]).map(x => x + 1)`

**Comment by robjens** [comment]
AFAIK (just got to learn this library), the only supported types are `Object` and `Array`.

Immutable `List` isn't to be found. Also the amount of available methods is seriously trimmed down. 

However, that having said, there is a way to accomplish what you desire, I've used ES5 function notation here...

```javascript
Immutable([1 2 3]).flatMap(function(x) { return x == 1 ? x + 1 : x; });
```

Should do the trick.

**Comment by rtfeldman** [comment]
I'd do what @robjens suggested! :+1: 

Happy to accept a PR adding this technique to the README, but closing this issue in the meantime.
