### ISSUE TITLE
Deep merge fails in non-trivial cases

### ISSUE THREAD

**Issue by ianp** [rtfeldman/seamless-immutable#55]
Unless I'm doing something daft (always a strong possibility!). Given

```js
var obj = Immutable({
  streams: {
    a: { name: "Conversations", channel: ["Facebook","Twitter"], loading: false},
    b: { name: "@Mentions", channel: ["Twitter"], loading: false},
    c: { name: "Facebook", channel: ["Facebook"], loading: false}
  },
  streamOrder: ["c", "a", "b"]
})
```

then running `j.merge({streams: {a: { loading: true }}}, true)` produces

```js
{
  streams: {
    a: { loading:true }
  },
  streamOrder: {0: "c", 1: "a", 2: "b"}
}
```

so instead of doing a deep merge it has thrown away all of the data under the `streams` key! Have I misunderstood how the deep merge is meant to work?

It's also converted the data under streamOder from an Array to an Object, but I can live with that for the time being :-)

**Comment by ianp** [comment]
FWIW a simpler example based on the one from your docs seems to do the right thing for me:
```js
Immutable({all: "your base", are: {belong: "to them"}}).merge({are: {belong: "to us"}}).merge({all: "the world"})
```
produces:
```js
{all: "the world", are: { belong: "to us"} }
```

**Comment by crudh** [comment]
@ianp: If you want to do a deep merge then the second argument shouldn't be `true`, it should be `{deep: true}` like:
```javascript
obj.merge({streams: {a: { loading: true }}}, {deep: true});
```

It produces the desired results.

**Comment by ianp** [comment]
Right you are, told you it was probably me doing something daft! Thanks!
