### ISSUE TITLE
How should I import this module from es6?

### ISSUE THREAD

**Issue by alesch** [rtfeldman/seamless-immutable#57]
Thanks for this module!

Importing like this in es5: `var I = require('seamless-immutable')` gives me:
```javascript
{ [Function: Immutable]
  isImmutable: [Function: isImmutable],
  ImmutableError: [Function: ImmutableError] }
```

but I do not find a way to get the same thing in es6.
Doing `import * as I from 'seamless-immutable'` gives:
```javascript
{ isImmutable: [Function: isImmutable],
  ImmutableError: [Function: ImmutableError],
  default: 
   { [Function: Immutable]
     isImmutable: [Function: isImmutable],
     ImmutableError: [Function: ImmutableError] } }
```
I can see that what I need is the `default` inside but I do not manage to get it
Thank you!.

**Comment by crudh** [comment]
@alesch: Does it work if you do: `import I from 'seamless-immutable'`

**Comment by alesch** [comment]
Using `new` it works, but it is ugly:
````javascript
import I from 'seamless-immutable'

let l = new I([1,2,3]);
console.log(l);   // [ 1, 2, 3 ]
```

When using [Ramda](http://ramdajs.com/) I do: `import * as R from 'ramda'` and it exposes all its functions under `R`.
I guess the difference is that seamless is not exposing a namespace, but a function.

**Comment by crudh** [comment]
I'm using babel and browserify and the following works for me:
```javascript
import I from "seamless-immutable";

const l = I([1, 2, 3]);
console.log(l);   // [1, 2, 3, __immutable_invariants_hold: true]
```

**Comment by alesch** [comment]
You are right, it works for me too with node. It was my IDE's linter complaining ?!?

In the beginning I tried using [nesh](http://danielgtaylor.github.io/nesh/), and there `import I from ...` does not work. But a regular `require` does.

Sorry about that and thanks for your help!

**Comment by crudh** [comment]
@alesch: nice! my IDE complains also if I do:
`import I from "seamless-immutable";`
but if I do:
`import immutable from "seamless-immutable";`
it doesnt. It's because functions with a name that starts with an uppercase letter are supposed to be constructor functions and used with `new`.

**Comment by alesch** [comment]
Super!

**Comment by jbmeslin** [comment]
Hi, 

how replace a require('seamless-immutable').static with and ES6 import  ?
