### ISSUE TITLE
Prod Mode

### ISSUE THREAD

**Issue by rtfeldman** [rtfeldman/seamless-immutable#6]
In production, it's probably unnecessary to actually freeze objects and throw exceptions when mutating methods are invoked. Those are mainly necessary in development, but by the time the code hits production, if any invariants aren't being followed, you should already know about it.

With that in mind, having a way to turn off the freezing and overriding should speed up performance, particularly in Safari. Adding a quick flag to turn this on would be useful to that end.

**Comment by diegovilar** [comment]
Agreed. Those constraints are mostly not supposed to be runtime errors and should be catch in development.

**Comment by crudh** [comment]
I'm interested in working on this but I am a bit unsure on how to pass the flag to the library?

Would you use the export code:
```
  if (typeof module === "object") {
    module.exports = Immutable;
  } else if (typeof exports === "object") {
    exports.Immutable = Immutable;
  } else if (typeof window === "object") {
    window.Immutable = Immutable;
  } else if (typeof global === "object") {
    global.Immutable = Immutable;
  }
```

To do different things depending on the environment, like (using global and window as examples):
```
  var prodMode = false;

  if (typeof module === "object") {
    module.exports = Immutable;
  } else if (typeof exports === "object") {
    exports.Immutable = Immutable;
  } else if (typeof window === "object") {
    window.Immutable = Immutable;
    prodMode = window.SEAMLESS_PROD_MODE === true;
  } else if (typeof global === "object") {
    global.Immutable = Immutable;
    prodMode = global.SEAMLESS_PROD_MODE === true;
  }
```

Or is there a better way?

**Comment by RangerMauve** [comment]
What about a method on Immutable that looks like `Immutable.setProduction(true/false)`, and then have people explicitly enable it and define their own way of detecting production mode?

**Comment by rtfeldman** [comment]
Awsesome!

The best practice I've seen (which is [what React does](http://stackoverflow.com/questions/25751045/react-and-grunt-envify-node-env-production-and-uglifyjs)) is to make it [envify](https://github.com/hughsk/envify)-friendly.

Basically you do this:

```
if (process.env.NODE_ENV === "development") {
  // do some stuff we wouldn't do in prod mode
}
```

...then run `envify` on it twice, once with `{NODE_ENV: "development"}` and once with `{NODE_ENV: "production"}` to get two output files: `seamless-immutable.development.js` and `seamless-immutable.production.min.js`

In the development build, `envify` will replace the above with this:

```
if ("development" === "development") {
  // do some stuff we wouldn't do in prod mode
}
```

....whereas in the production build, it will instead replace it with this:

```
if ("production" === "development") {
  // do some stuff we wouldn't do in prod mode
}
```

[Uglify](https://github.com/mishoo/UglifyJS2) will then see that this conditional will always fail and will strip this code out entirely, meaning the production build will not only avoid adding the extra attributes, it won't even run any conditionals to tell if it's in prod mode!

This implicitly means we'd need to introduce a build process to generate the two different files for library consumers.

**Comment by alanhogan** [comment]
I've been wondering about how to do this kind of thing for ever. Very nice solution. No non-JS syntax needed. 

Alan

**Comment by crudh** [comment]
Should we then move `seamless-immutable.js` to a `src` directory to indicate that it shouldn't be used directly? And place the output files of `envify` in the root?

**Comment by rtfeldman** [comment]
That makes sense to me. Let's not check in changes to the compiled files on every commit, though, as that will make the diffs miserable.

Instead just leave them out of normal commits, and once per release I'll include updated compiled files in the commit that bumps the version number.

Sound good?

**Comment by crudh** [comment]
Sounds good!
