### ISSUE TITLE
instanceof checks can cause issues

### ISSUE THREAD

**Issue by WickyNilliams** [rtfeldman/seamless-immutable#61]
Using `instanceof` to check for arrays etc. can cause issues across frame boundaries. Each document has a different context so one array may not be an `instanceof` another.

```js
var frame = document.createElement("iframe");

frame.onload = function(e) {
  console.log([] instanceof frame.contentWindow.Array); // false
}

document.body.appendChild(frame);
```

**Comment by rtfeldman** [comment]
Hm, I don't quite follow the case where this could cause a problem for `seamless-immutable`.

Could you show a code example where this would lead `seamless-immutable` to behave undesirably?
