### ISSUE TITLE
Implement set, setIn, mergeIn

### ISSUE THREAD

**Issue by smashercosmo** [rtfeldman/seamless-immutable#64]
It's really hard to use seamless-immutable without these methods. Any plans to implement them?

**Comment by ellis** [comment]
I was just looking for this too, also for arrays.

**Comment by tusharmath** [comment]
Must needed.

**Comment by rtfeldman** [comment]
Happy to accept PRs for these! I believe @jlongster may have already made some progress on this?

**Comment by rtfeldman** [comment]
Closing thanks to https://github.com/rtfeldman/seamless-immutable/pull/69
