### ISSUE TITLE
Rename 'without' to 'omit' for lodash/underscore compatibility

### ISSUE THREAD

**Issue by plestik** [rtfeldman/seamless-immutable#66]
Is it possible to rename `without` to `omit` for lodash/underscore compatibility? 

https://lodash.com/docs#without
https://lodash.com/docs#omit

**Comment by rtfeldman** [comment]
I'd have been open to this back in the 1.0 days, but I can't justify a breaking change like this now that we're at 4.0. :)

Sorry!

**Comment by CosticaPuntaru** [comment]
it can have an alias ...
