### ISSUE TITLE
Performance Hit while merging really large JS objects even when merge deep is set to false 

### ISSUE THREAD

**Issue by tusharmath** [rtfeldman/seamless-immutable#72]
![screen shot 2015-10-20 at 1 32 05 pm](https://cloud.githubusercontent.com/assets/194482/10601393/0332acae-772f-11e5-8fdf-22d14841742e.png)

**Scenario**

Recieved a huge JSON response from an API request.

**Problem**

While setting the response as a JS object, into an immutable store via `merge` — the function converts the huge object to an Immutable recurrsively. This is causes performance issues and makes the rendering slow.

Ideally if the user has set `{deep: false}` at the time of merging, it should not try to convert recursively.

**Comment by rtfeldman** [comment]
Is the proposed solution that the Immutable would hold a mutable object?

**Comment by tusharmath** [comment]
I am not sure about this. There could be so many cases where you want to store it as an immutable. Though in this case we don't need it to be immutable.

**Comment by rtfeldman** [comment]
What I meant was - could there possibly be any other solution to the stated
problem besides leaving it as a mutable object?

**Comment by tusharmath** [comment]
No. As per the above profiling it seems like the recursive conversion to Immutable takes a lot of time. I started facing this issue when I had a huge array of numbers that I wanted to plot on a graph.

How about doing it asynchronously?

**Comment by rtfeldman** [comment]
If asynchronous is a solution, that can already be done; if you pass an immutable instance to `Immutable`, it just uses the one it's given and doesn't recurse.

As a next step, I'd suggest trying that (just iterate over the object you're given and recurse asynchronously until you've built up what you need) and see if that solves the problem.
