### ISSUE TITLE
Cache NODE_ENV to improve performance

### ISSUE THREAD

**Issue by sudhakar** [rtfeldman/seamless-immutable#74]
Accessing ```process.env.NODE_ENV``` property incurs significant performance overhead. See https://github.com/facebook/react/issues/812

**Comment by rtfeldman** [comment]
The production build has all references to NODE_ENV stripped out by envify, so this won't be a concern there.

Is there a reason you couldn't address the performance concern by using the prod build?

**Comment by rtfeldman** [comment]
Closing now that #75 exists; let's continue discussion there.
