### ISSUE TITLE
Incompatible with Object.create(null)

### ISSUE THREAD

**Issue by lzrski** [rtfeldman/seamless-immutable#76]
Hello. Thanks for seamless. It's a very nice piece of software.

I was surprised however that I cannot create immutable object from an object without prototype (e.g. acquired with `Object.create(null)`:

```javascript
Immutable(Object.create(null));
// TypeError: target.hasOwnProperty is not a function
```

It is also impossible to merge such an object into `immutable`:

```javascript
var o1 = Immutable({a: 1});
var o2 = Object.create(null);
o2.b = 2;
o1.merge(o2);
// TypeError: other.hasOwnProperty is not a function
```

Obviously it depends on `hasOwnProperty` method of the original object, which is usually available in a prototype chain.

Can we use global `Object` methods instead, like `Object.getOwnPropertyDescriptor`? I'll be happy to provide PR, but would like to discuss it first.

**Comment by rtfeldman** [comment]
I'm surprised by this too! Assuming it wouldn't have noticeable performance costs, I'd be happy to accept a PR that fixed this.
