### ISSUE TITLE
exporting as module for systemjs

### ISSUE THREAD

**Issue by fxck** [rtfeldman/seamless-immutable#77]
any way to import seamless-immutable with systemjs?

**Comment by fxck** [comment]
basically adding umd.. like this perhaps https://github.com/fxck/seamless-immutable/commits/master it's failing tests now though.. but it works

**Comment by veggiemonk** [comment]
:+1:

**Comment by rtfeldman** [comment]
I'd definitely be open to a pull request for this, but I'm gonna close the issue in the meantime. Thanks!
