### ISSUE TITLE
Opt-out of array merging

### ISSUE THREAD

**Issue by amannn** [rtfeldman/seamless-immutable#79]
Is there a way to opt-out of the array merging?

**Comment by crudh** [comment]
What do you mean? If you merge A with B and both contain the array named C then the result will contain the array from B. Do you want the result to ignore the array from B and keep the array from A?

**Comment by amannn** [comment]
I'd like to do something like this:

```
let o = Immutable({arr: [{id: 2}]});
o.merge({arr: [{id: 3}]}, {mergeArray: false});
// o is {arr: [{id: 3}]}
```

So the array from B should override the array from A.

With the current implementation the result is `{arr: [{id: 2}, {id: 3}]}`

**Comment by crudh** [comment]
This is my output when I test with 3.0.0 and 4.0.2: 
```
var o = immutable({arr: [{id: 2}]});
o = o.merge({arr: [{id: 3}]});
// o is {arr: [{id: 3}]}
```

**Comment by amannn** [comment]
Oh, you're of course totally right! Sorry for the annoyance – I mixed this up with another library. Everything works as expected.
