### ISSUE TITLE
Prod and dev files are out of date

### ISSUE THREAD

**Issue by crudh** [rtfeldman/seamless-immutable#89]
After the merge of #78 the source file is updated with freezing of dates but no updated versions of the prod and dev builds have been generated and committed. So those that doesn't use the source file are missing the functionality.

@rtfeldman should I include the generated files in future PRs? It's very easy to forget about that step before doing a release.

**Comment by rtfeldman** [comment]
Oh weird. Thought I did that. Probably a good idea, yeah, but ultimately something I ought to do.

**Comment by rtfeldman** [comment]
Published as 5.0.1.

**Comment by rtfeldman** [comment]
Thanks @crudh!

**Comment by crudh** [comment]
@rtfeldman :+1: nice, 4 minutes from report to release :smile:
