### ISSUE TITLE
Produce a minified version of the development artifact.

### ISSUE THREAD

**Issue by InsomniacFury** [rtfeldman/seamless-immutable#91]
@rtfeldman 
I appreciate the clarification you provided in #90.

Tying it together with your recommendation in https://github.com/rtfeldman/seamless-immutable/pull/86#issuecomment-170627098, I would like to keep the enforcement of immutablity in production.

To provide some context, I'm in the process of introducing your library into production and host it on our CDN. Similar to the minification you already provide for production artifact, being able to clone this repo without any additional post-processing or forking to set up post processing would be convenient.

Thoughts on this request?

Also, I would like to add your library has helped provide ~85% performance gain for operation I am employing it for. :+1:

**Comment by rtfeldman** [comment]
> Also, I would like to add your library has helped provide ~85% performance gain for operation I am employing it for. :+1:

Awesome, glad to hear it! :smile_cat:

**Comment by rtfeldman** [comment]
So to clarify, the request is for a new `seamless-immutable.development.min.js` file, which is a minified version of `seamless-immutable.development.js`?

**Comment by InsomniacFury** [comment]
@rtfeldman correct.

**Comment by rtfeldman** [comment]
I'm worried this will create confusion as to which version to use in which circumstance. All the other use cases I'm aware of have been either folks using the existing production build, or else the development build run through their own minification process.

I realize it would be convenient for your use case, but I would rather keep this simple: use the `development.js` build for development and the `production.min.js` build for production. Apologies!
