### ISSUE TITLE
Add the license to the top of the minified artifacts

### ISSUE THREAD

**Issue by InsomniacFury** [rtfeldman/seamless-immutable#92]
This ties to #91.  

Along the same notion of aiming to consume this library in production, it would be helpful if as part of your artifact generation step, it could also add https://github.com/rtfeldman/seamless-immutable/blob/master/LICENSE to make it easier for consumers to abide by the license.

**Comment by rtfeldman** [comment]
Thanks for the idea, but I prefer minified files to be as small as possible, including removing comments...and I'm not super worried about license enforcement. :smile:

**Comment by fenduru** [comment]
@rtfeldman if you're not worried about license enforcement, then you should use a license that does not mandate that `* Redistributions of source code must retain the above copyright notice, this
  list of conditions and the following disclaimer.`

The intuitive use of this repository would be to ship with the `.production.min.js` file, which by default is in violation of your own license

**Comment by fenduru** [comment]
An alternative approach that jquery uses is to have a small comment linking to the full license:

**Comment by rtfeldman** [comment]
Good call! Link to the license seems reasonable; that's only a few extra bytes. Would happily accept a PR for that! :smiley:
