### ISSUE TITLE
Document additions/modifications to (Array|Object).prototype

### ISSUE THREAD

**Issue by danny-andrews** [rtfeldman/seamless-immutable#95]
In the docs, it reads:

``` markdown
1. All the methods that would normally mutate the data structures instead throw ImmutableError.
2. All the methods that return a relevant value now return an immutable equivalent of that value.
3. Attempting to reassign values to their elements (e.g. foo[5] = bar) will not work. Browsers other than Internet Explorer will throw a TypeError if use strict is enabled, and in all other cases it will fail silently.
4. A few additional methods have been added for convenience.
```

Modifying built-in behavior of basic data structures is a pretty big deal, so it would be nice to have an exhaustive list of the modified/added methods in 1, 2, and 4.

**Comment by rtfeldman** [comment]
Fair enough. Happy to accept a PR for this! :smile:

**Comment by estaub** [comment]
(noob here, hopefully not too off-topic) It would be good to know (without testing) whether static object/array methods like Object.keys() will work.  Nothing in the readme leads me to guess one way or the other.

**Comment by crudh** [comment]
@estaub yes, they will work. All objects and arrays are normal javascript objects and arrays with the exception that they are frozen and mutating methods throw errors.

**Comment by danny-andrews** [comment]
I actually don't think enumerating the modified built-in methods is that important anymore. The purpose of the library implies it's going to be doing that stuff. It's more important to know which methods have been **added** to the prototype (which is already documented). Although, from the examples, it's not clear that `Array.prototype` is modified, since the `Immutable.METHOD_NAME` version is used. Example: https://github.com/rtfeldman/seamless-immutable#flatmap.
